const api=path=>`${location.origin}/api/v1${path}`;const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const login=document.querySelector('#account-login'),content=document.querySelector('#account-content'),message=document.querySelector('#login-message'),requestForm=document.querySelector('#login-request'),verifyForm=document.querySelector('#login-verify'),ordersBox=document.querySelector('#account-orders'),detailBox=document.querySelector('#account-detail');let email='';
const call=async(path,options={})=>{const response=await fetch(api(path),{credentials:'include',headers:{Accept:'application/json','Content-Type':'application/json',...(options.headers||{})},...options});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`http_${response.status}`);return body};
const showMessage=text=>{message.textContent=text};
async function loadAccount(){try{const me=await call('/customer/auth/me');login.classList.add('hidden');content.classList.remove('hidden');document.querySelector('#account-name').textContent=me.customer.display_name||me.customer.name||'Cliente';document.querySelector('#account-email').textContent=me.customer.email;const result=await call('/customer/orders');const rows=result.data||[];ordersBox.innerHTML=`<strong>Meus pedidos</strong>${rows.length?`<div class="account-orders">${rows.map(order=>`<button class="account-order" data-id="${esc(order.id)}" type="button"><span>Pedido #${esc(order.order_number)}</span><span>${esc(order.status)} · R$ ${Number(order.total).toFixed(2).replace('.',',')}</span></button>`).join('')}</div>`:'<span>Você ainda não possui pedidos.</span>'}`;ordersBox.querySelectorAll('[data-id]').forEach(button=>button.addEventListener('click',()=>loadDetail(button.dataset.id)))}catch{login.classList.remove('hidden');content.classList.add('hidden')}}
async function loadDetail(id){try{const result=await call(`/customer/orders/${encodeURIComponent(id)}`);const order=result.data;detailBox.classList.remove('hidden');detailBox.innerHTML=`<strong>Pedido #${esc(order.order_number)}</strong><span>Status: ${esc(order.status)} · Total: R$ ${Number(order.total).toFixed(2).replace('.',',')}</span><ul>${order.items.map(item=>`<li>${esc(item.quantity)} × ${esc(item.name)}</li>`).join('')}</ul><button class="account-button" data-reorder type="button">Pedir novamente</button>`;detailBox.querySelector('[data-reorder]').addEventListener('click',()=>{localStorage.setItem('petisbar.reorderItems',JSON.stringify(order.items.map(item=>({productId:item.product_id,name:item.name,quantity:item.quantity,options:item.options}))));location.href='../cardapio.html'})}catch{showMessage('Não foi possível carregar este pedido.')}}
requestForm.addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(requestForm);email=String(data.get('email')).trim().toLowerCase();try{await call('/customer/auth/request-login',{method:'POST',body:JSON.stringify({email,name:String(data.get('name')||'').trim()})});requestForm.classList.add('hidden');verifyForm.classList.remove('hidden');showMessage('Código enviado. Confira seu e-mail.')}catch{showMessage('Não foi possível enviar o código.')}});
verifyForm.addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(verifyForm);try{await call('/customer/auth/verify',{method:'POST',body:JSON.stringify({email,code:String(data.get('code')).trim()})});await loadAccount()}catch{showMessage('Código inválido ou expirado.')}});
document.querySelector('#logout').addEventListener('click',async()=>{await call('/customer/auth/logout',{method:'POST'});location.reload()});loadAccount();
