import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { requirePermission } from '../middleware/auth.js';
const profileSchema=z.object({razao:z.string().max(200).default(''),fantasia:z.string().max(200).default(''),cnpj:z.string().max(20).default(''),cnae:z.string().max(30).default(''),atividade:z.enum(['comercio','servico','ambos']).default('comercio'),municipio:z.string().max(120).default(''),uf:z.string().max(2).default(''),ie:z.string().max(30).default(''),im:z.string().max(30).default(''),contadorNome:z.string().max(200).default(''),contadorCrc:z.string().max(30).default(''),contadorEmail:z.string().email().or(z.literal('')).default(''),contadorTelefone:z.string().max(40).default('')});
const docSchema=z.object({documentType:z.enum(['entrada','saida','servico']),number:z.string().max(80).default(''),series:z.string().max(30).default(''),issueDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),counterparty:z.string().min(1).max(200),counterpartyTaxId:z.string().max(20).default(''),amount:z.number().nonnegative().max(9999999999),xmlUrl:z.string().max(500).default(''),status:z.enum(['pendente','validado','cancelado']).default('pendente'),notes:z.string().max(1000).default('')});
const obligationSchema=z.object({competence:z.string().regex(/^\d{4}-\d{2}-01$/),type:z.enum(['das_mei','dasn_simei','relatorio_receita_bruta']),dueDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),amount:z.number().nonnegative().max(9999999999).default(0),status:z.enum(['aberta','paga','transmitida','cancelada']).default('aberta'),receiptNumber:z.string().max(100).default(''),notes:z.string().max(1000).default('')});
const dt=v=>v instanceof Date?v.toISOString().slice(0,10):String(v||'').slice(0,10);
const doc=r=>({id:r.id,documentType:r.document_type,number:r.document_number,series:r.series,issueDate:dt(r.issue_date),counterparty:r.counterparty_name,counterpartyTaxId:r.counterparty_tax_id,amount:Number(r.amount),xmlUrl:r.xml_url,status:r.status,notes:r.notes});
const obl=r=>({id:r.id,competence:dt(r.competence),type:r.obligation_type,dueDate:dt(r.due_date),amount:Number(r.amount),status:r.status,receiptNumber:r.receipt_number,notes:r.notes});
export default async function accountingFiscalRoutes(app){const read=requirePermission('accounting.read'),write=requirePermission('accounting.write');
app.get('/accounting-fiscal/profile',{preHandler:read},async()=>{const {rows}=await app.db.query("SELECT value FROM app_settings WHERE key='accountingFiscalProfile'");return{data:rows[0]?.value||{}}});
app.put('/accounting-fiscal/profile',{preHandler:write},async(req,reply)=>{const p=profileSchema.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'validation_error',details:p.error.flatten()});await app.db.query("INSERT INTO app_settings(key,value) VALUES('accountingFiscalProfile',$1::jsonb) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()",[JSON.stringify(p.data)]);await app.db.query("INSERT INTO audit_logs(user_id,action,entity_type,metadata,ip) VALUES($1,'accounting.profile.update','company',$2,$3)",[req.user.id,{fields:Object.keys(p.data)},req.ip]);return{data:p.data}});
app.get('/accounting-fiscal/documents',{preHandler:read},async()=>{const {rows}=await app.db.query('SELECT id,document_type,document_number,series,issue_date::text,counterparty_name,counterparty_tax_id,amount,xml_url,status,notes FROM fiscal_documents ORDER BY issue_date DESC,created_at DESC LIMIT 500');return{data:rows.map(doc)}});
app.post('/accounting-fiscal/documents',{preHandler:write},async(req,reply)=>{const p=docSchema.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'validation_error',details:p.error.flatten()});const d=p.data,id='fdoc-'+randomUUID();const {rows}=await app.db.query('INSERT INTO fiscal_documents(id,document_type,document_number,series,issue_date,counterparty_name,counterparty_tax_id,amount,xml_url,status,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id,document_type,document_number,series,issue_date::text,counterparty_name,counterparty_tax_id,amount,xml_url,status,notes',[id,d.documentType,d.number,d.series,d.issueDate,d.counterparty,d.counterpartyTaxId,d.amount,d.xmlUrl,d.status,d.notes,req.user.id]);await app.db.query("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,ip) VALUES($1,'accounting.document.create','fiscal_document',$2,$3)",[req.user.id,id,req.ip]);return reply.code(201).send({data:doc(rows[0])})});
app.delete('/accounting-fiscal/documents/:id',{preHandler:write},async(req,reply)=>{const id=z.string().min(1).max(100).safeParse(req.params.id);if(!id.success)return reply.code(400).send({error:'validation_error'});const r=await app.db.query('DELETE FROM fiscal_documents WHERE id=$1',[id.data]);if(!r.rowCount)return reply.code(404).send({error:'document_not_found'});await app.db.query("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,ip) VALUES($1,'accounting.document.delete','fiscal_document',$2,$3)",[req.user.id,id.data,req.ip]);return reply.code(204).send()});
app.get('/accounting-fiscal/obligations',{preHandler:read},async()=>{const {rows}=await app.db.query('SELECT id,competence::text,obligation_type,due_date::text,amount,status,receipt_number,notes FROM tax_obligations ORDER BY due_date DESC LIMIT 500');return{data:rows.map(obl)}});
app.post('/accounting-fiscal/obligations',{preHandler:write},async(req,reply)=>{const p=obligationSchema.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'validation_error',details:p.error.flatten()});const d=p.data,id='obl-'+randomUUID();try{const {rows}=await app.db.query('INSERT INTO tax_obligations(id,competence,obligation_type,due_date,amount,status,receipt_number,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,competence::text,obligation_type,due_date::text,amount,status,receipt_number,notes',[id,d.competence,d.type,d.dueDate,d.amount,d.status,d.receiptNumber,d.notes]);await app.db.query("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,ip) VALUES($1,'accounting.obligation.create','tax_obligation',$2,$3)",[req.user.id,id,req.ip]);return reply.code(201).send({data:obl(rows[0])})}catch(e){if(e.code==='23505')return reply.code(409).send({error:'obligation_already_exists'});throw e}});
app.patch('/accounting-fiscal/obligations/:id',{preHandler:write},async(req,reply)=>{const id=z.string().min(1).max(100).safeParse(req.params.id),p=obligationSchema.safeParse(req.body);if(!id.success||!p.success)return reply.code(400).send({error:'validation_error'});const d=p.data;const {rows}=await app.db.query('UPDATE tax_obligations SET competence=$2,obligation_type=$3,due_date=$4,amount=$5,status=$6,receipt_number=$7,notes=$8 WHERE id=$1 RETURNING id,competence::text,obligation_type,due_date::text,amount,status,receipt_number,notes',[id.data,d.competence,d.type,d.dueDate,d.amount,d.status,d.receiptNumber,d.notes]);if(!rows[0])return reply.code(404).send({error:'obligation_not_found'});await app.db.query("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,ip) VALUES($1,'accounting.obligation.update','tax_obligation',$2,$3)",[req.user.id,id.data,req.ip]);return{data:obl(rows[0])}});
app.get('/accounting-fiscal/monthly-report',{preHandler:read},async(req,reply)=>{const p=z.object({month:z.string().regex(/^\d{4}-\d{2}$/)}).safeParse(req.query);if(!p.success)return reply.code(400).send({error:'validation_error'});const {rows}=await app.db.query("SELECT entry_date::text AS date,description,category,entry_type,amount FROM financial_entries WHERE entry_date >= $1::date AND entry_date < ($1::date + interval '1 month') ORDER BY entry_date,created_at",[p.data.month+'-01']);const entries=rows.map(r=>({date:r.date,description:r.description,category:r.category,type:r.entry_type,value:Number(r.amount)}));let sales=0,otherIncome=0,expenses=0;for(const e of entries){if(e.category==='Vendas'&&e.type==='Entrada')sales+=e.value;else if(e.value>0)otherIncome+=e.value;else expenses+=Math.abs(e.value)}return{data:{month:p.data.month,sales,otherIncome,expenses,result:sales+otherIncome-expenses,entries,notice:'Relatório gerencial de apoio; não substitui escrituração, apuração tributária ou declaração oficial.'}}});}

